In [57]:
!pip install pandas-diff

Collecting pandas-diff
  Using cached pandas_diff-1.4.7-py2.py3-none-any.whl
Requirement already satisfied: Click>=7.0 in /Users/john/.virtualenvs/c477/lib/python3.11/site-packages (from pandas-diff) (8.1.7)
Requirement already satisfied: pandas in /Users/john/.virtualenvs/c477/lib/python3.11/site-packages (from pandas-diff) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/john/.virtualenvs/c477/lib/python3.11/site-packages (from pandas->pandas-diff) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/john/.virtualenvs/c477/lib/python3.11/site-packages (from pandas->pandas-diff) (2023.3.post1)
Requirement already satisfied: numpy>=1.21.0 in /Users/john/.virtualenvs/c477/lib/python3.11/site-packages (from pandas->pandas-diff) (1.26.0)
Requirement already satisfied: six>=1.5 in /Users/john/.virtualenvs/c477/lib/python3.11/site-packages (from python-dateutil>=2.8.1->pandas->pandas-diff) (1.16.0)
Installing collected packages: pandas-diff
Successfully installed pandas-diff-1.4.7

In [58]:
import pandas as pd

In [112]:
# prod = pd.read_csv('stg_epc_certificates-prod.csv', low_memory=False)
prod = pd.read_csv("stg_os_places-john.csv", low_memory=False)

In [113]:
# new = pd.read_csv('stg_epc_certificates-john.csv', low_memory=False)
new = pd.read_csv("stg_os_places-prod.csv", low_memory=False)

In [114]:
prod.shape

(90776, 40)

In [115]:
new.shape

(90776, 40)

In [119]:
# prod = prod.sort_values('lmk_key').reset_index(drop=True)
# new = new.sort_values('lmk_key').reset_index(drop=True)

prod = prod.sort_values(["uprn", "postcode"]).reset_index(drop=True)
new = new.sort_values(["uprn", "postcode"]).reset_index(drop=True)

In [120]:
prod.head(3)

,rpc,postcode,logical_status_code,country_code_description,x_coordinate,last_update_date,classification_code_description,organisation_name,udprn,status,...,y_coordinate,match_description,classification_code,entry_date,match,country_code,_airbyte_ab_id,_airbyte_emitted_at,_airbyte_normalized_at,_airbyte_os_places_api_hashid
0,1,PO3 5HU,8,This record is within England,466265.0,10/02/2016,Workshop / Light Industrial,NaN,19183368,HISTORICAL,...,104169.0,EXACT,CI03,18/12/2000,1,E,659bfc49-fed3-4c84-9b2a-f4510ea921ff,2023-09-15 22:26:10.041000 +00:00,2023-09-15 22:28:06.161370 +00:00,a518851dbbf1ae679e602e11eb4ecd55
1,2,PO3 5JP,1,This record is within England,466267.0,22/06/2022,Warehouse / Store / Storage Depot,NaN,19183524,APPROVED,...,104247.0,EXACT,CI04,18/12/2000,1,E,c8ddb1e5-8202-4f97-86b8-dc29f741b8cb,2023-09-15 22:26:12.771000 +00:00,2023-09-15 22:28:06.161370 +00:00,cde4ff8980be18f067fc383004f986b5
2,1,PO3 5JP,1,This record is within England,466248.0,22/06/2022,Factory/Manufacturing,RE WORX,19183525,APPROVED,...,104248.0,EXACT,CI01,18/12/2000,1,E,a6593ce7-a258-47fe-a663-725dfb83e12d,2023-09-15 22:26:05.714000 +00:00,2023-09-15 22:28:06.161370 +00:00,f23200b6568f086f9c1f940ec95a97f8

In [121]:
new.head(3)

,rpc,postcode,logical_status_code,country_code_description,x_coordinate,last_update_date,classification_code_description,organisation_name,udprn,status,...,y_coordinate,match_description,classification_code,entry_date,match,country_code,_airbyte_ab_id,_airbyte_emitted_at,_airbyte_normalized_at,_airbyte_os_places_api_hashid
0,1,PO3 5HU,8,This record is within England,466265.0,10/02/2016,Workshop / Light Industrial,NaN,19183368,HISTORICAL,...,104169.0,EXACT,CI03,18/12/2000,1,E,659bfc49-fed3-4c84-9b2a-f4510ea921ff,2023-09-15 22:26:10.041000 +00:00,2023-09-15 22:28:06.161370 +00:00,a518851dbbf1ae679e602e11eb4ecd55
1,2,PO3 5JP,1,This record is within England,466267.0,22/06/2022,Warehouse / Store / Storage Depot,NaN,19183524,APPROVED,...,104247.0,EXACT,CI04,18/12/2000,1,E,c8ddb1e5-8202-4f97-86b8-dc29f741b8cb,2023-09-15 22:26:12.771000 +00:00,2023-09-15 22:28:06.161370 +00:00,cde4ff8980be18f067fc383004f986b5
2,1,PO3 5JP,1,This record is within England,466248.0,22/06/2022,Factory/Manufacturing,RE WORX,19183525,APPROVED,...,104248.0,EXACT,CI01,18/12/2000,1,E,a6593ce7-a258-47fe-a663-725dfb83e12d,2023-09-15 22:26:05.714000 +00:00,2023-09-15 22:28:06.161370 +00:00,f23200b6568f086f9c1f940ec95a97f8

In [122]:
set(prod.columns).difference(new.columns)

set()

In [123]:
set(new.columns).difference(prod.columns)

set()

In [124]:
# prod = prod.rename(columns={'LANGUAGE': 'language', 'MATCH': 'match'})

In [125]:
prod.compare(new)

Empty DataFrame
Columns: []
Index: []

In [126]:
new.lmk_key.duplicated().sum()

AttributeError: 'DataFrame' object has no attribute 'lmk_key'

In [127]:
prod.lmk_key.duplicated().sum()

AttributeError: 'DataFrame' object has no attribute 'lmk_key'

In [128]:
new.uprn.duplicated().sum()

0

In [129]:
prod.uprn.duplicated().sum()

0

In [130]:
new.loc[373].uprn

1775001977

In [131]:
new[new.uprn.duplicated()].uprn

Series([], Name: uprn, dtype: int64)

In [132]:
prod[prod.uprn.duplicated()].uprn

Series([], Name: uprn, dtype: int64)

In [133]:
# from dataframe_diff import dataframe_diff

In [134]:
# d1_column,d2_additional = dataframe_diff(prod, new, key='uprn')

In [135]:
import pandas_diff as pd_diff

In [136]:
prod.shape

(90776, 40)

In [137]:
new.shape

(90776, 40)

In [141]:
%%time
N = 100000

# Get differences, using the key "hero"
# df = pd_diff.get_diffs(prod.head(N) ,new.head(N) ,"lmk_key")
df = pd_diff.get_diffs(prod.head(N), new.head(N), "uprn")

CPU times: user 29.5 s, sys: 361 ms, total: 29.8 s
Wall time: 32.9 s

In [142]:
df

Empty DataFrame
Columns: []
Index: []

In [143]:
prod.equals(new)

True